Repository DD2480-Group-15-vt24/2-CI, pull requests merged in 2024-02, with the labels that each got.

#2 Feat: setup initial repo structure #1
  .github/workflows/ci-testing.yml
  README.md
  docs/README.md
  main.py
  plan.md
  requirements.txt
  src/__init__.py
  tests/__init__.py
Labels: enhancement

#4 Feat: add fastapi server that formats repository on webhook #3
  README.md
  main.py
  requirements.txt
  src/format.py
  tests/test_format.py
Labels: enhancement

#6 Feat: add another endpoint that tests the repo using pytest #5
  README.md
  main.py
  src/black.py
  src/cmd.py
  src/git.py
  src/pytest.py
  tests/test_black.py
  tests/test_git.py
  tests/test_pytest.py
  tests/test_webhook.py
Labels: enhancement

#18 Fix: Substitute python version to 3.8.10
  .github/workflows/ci-testing.yml
  .python-version
  README.md
  src/cmd.py
  tests/test_pytest.py
Labels: bug

#17 Fix: Changed network port
  main.py
Labels: invalid

#20 Fix: Added operating directives and a new contributor
  README.md
Labels: documentation

#22 doc: Add 'Way of Working' section to README
  README.md
Labels: documentation

#21 Feat: Set commit status using GitHub REST API
  docs/README.md
  main.py
  requirements.txt
  src/notification.py
  tests/test_notification.py
  tests/test_webhook.py
Labels: enhancement

#25 Fix: Read API token from file
  .gitignore
  docs/README.md
  main.py
  src/notification.py
  tests/test_notification.py
Labels: bug

#26 feat: Add HTML documentation files for project documentation
  html/main.html
  html/src/black.html
  html/src/cmd.html
  html/src/format.html
  html/src/git.html
  html/src/index.html
  html/src/notification.html
  html/src/pytest.html
Labels: documentation, enhancement

#30 Fix: Add comments to function and classes in github.py
  src/github.py
Labels: documentation

#32 Fix: Add comments to main
  main.py
Labels: documentation
